region: nwa
product: global-analysis-forecast-phy-001-024
dataset:
  currents:
    dataset_id: cmems_mod_glo_phy-cur_anfc_0.083deg_P1D-m:
    vars: 
      - vo
      - uo
    depth:
      - 0
      - 10
  surface:
    dataset_id: cmems_mod_glo_phy_anfc_0.083deg_P1D-m:
    vars:
      - ist
      - mlotst
      - pbo
      - siage
      - sialb
      - siconc
      - sisnthick
      - sithick
      - sivelo
      - sob
      - tob
      - usi
      - vsi
      - zos
    depth:
      - 0
      - 10
      
log_level: WARN
