#' Write a copernicus file given a stars object, database and path
#' 
#' @export
#' @param x a stars object
#' @param db database table
#' @param path chr, the output data path used by [compose_filename]
#' @param check_path logical, if TRUE then make sure the output path exists.  Note 
#'   the final output path is generated by [compose_filename] and may not be the same
#'   as `path`.
#' @return the input stars object
write_copernicus = function(x, db, path = ".", check_path = TRUE){
  fname = compose_filename(db, path)
  if (check_path) ok = make_path(dirname(fname))
  stars::write_stars(x, fname)
}

#' Read one or more copernicus files
#' 
#' By default the function tries to return an object with (variables of x, y, time) 
#' dimensions.  If multiple times are provided, then each var must be equally
#' represented.
#' 
#' @export
#' @param db tibble, database of selected records
#' @param path char, the path to the data set
#' @return stars object
read_copernicus = function(db, path){
  
  db$datetime = as.POSIXct(paste(format(db$date, '%Y-%m-%d'), db$time), 
                       format = "%Y-%m-%d %H%M%S", tz = 'UTC')  
  db$file = compose_filename(db, path)
  # read each variable
  # check that each variable has the same time-dim
  # if ok then bind, otherwise error
  db |>
    dplyr::group_by(.data$variable) |>
    dplyr::group_map(
      function(tbl, key){
        if (nrow(tbl) > 1 ){
          s = stars::read_stars(tbl$file, along = list(time = tbl$datetime)) |>
            rlang::set_names(tbl$variable[1])
        } else {
          s = stars::read_stars(tbl$file) |>
            rlang::set_names(tbl$variable[1])
        }
      }, .keep = TRUE) |>
    bind_stars()
}


#' Unpack a copernicus ncdf4 file
#'
#' @export
#' @param filename character, the full path specification
#' @param banded logical, see \code{\link{get_var}}.  Setting to FALSE
#'        returns single band objects (depth and time dropped)
#' @param bind logical, if TRUE bind the outputs into one stars object
#' @return list of \code{stars} objects
unpack_copernicus <- function(filename, banded = FALSE, bind = TRUE){
  #x <- ncdf4::nc_open(filename[1])
  #ss <- sapply(get_varnames(x),
  #             function(vname){
  #               get_var(x, var = vname, banded = banded)
  #             },
  #             simplify = FALSE)
  #ncdf4::nc_close(x)
  #if (bind) ss = bind_stars(ss)
  stars::read_stars(filename)
}

